void slapperControl();
void intakeControl();
void wingTeleControl();
void blockerControl(bool state);
void blockerTeleControl();  
void BwingTeleControl();
void chomperTelecontrol();
void setIntake(int speed);
void wingControl(bool state);
void BwingControl(bool state);
void matchLoad(bool matchLoading, bool skills);